### ISSUE TITLE
Add better styling and rendering utilities

### ISSUE THREAD

**Issue by noahmayr** [sayanarijit/xplr#564]
We can already do quite a lot with the style, border and meta configurations for panels/nodes, however formatting and display utilities are limited in custom renderers.

Suggested rendering utility functions
- [x] `xplr.util.style(string, style)` apply the style object to the given string. This could be done in lua, but since you most likely already have rust code for formatting a string using a style, it'd be better to expose this functionality so it behaves exactly the same way. (see #566)
- [x] `xplr.util.wrap(text, width)` (this should handle multibyte characters like nerdfont icons as well as ansi formatting codes, maybe this can help https://github.com/mgeisler/textwrap. I've attempted to do this in lua, but I'm pushing against the limits of lua string processing). Ideally this could even support wrapping on words or characters (see #567)
- [ ] `xplr.util.strip_ansi(string)` remove all ansi escape codes. (Nice to have, could be done in lua though)
- [x] Allow getting additional metadata for any node (e.g. to get the correct meta.icon and style of the resolved symlink target or to see if the node is selected or focused), mainly the following fields would be interesting: is_focused, is_selected as well as meta and style using xplr's resolution based on nodetype, extension and mimetype. This would also allow a custom layout accessing `ctx.app.focused_node` to get the right metadata for it
- [x] Allow disabling automatic row styling based on node type (I would prefer only applying the node style to the path column and with `xplr.util.style()` and being able to disable automatic styling I could apply it myself in the column renderer)

General missing utilities
- [x] `xplr.util.relative` given an absolute path returns the relative path to the current dir (see #568)

**Comment by sayanarijit** [comment]
The utility functions sounds good.
Regarding xplr.util.relative, I assume it is different than xplr.util.basename.

Other issues regarding metadata and disabling style, it could require more discussions and maybe some experiments. So I'd create a separate issue for those, and keep this issue only for the proposed utility functions.

Since we're using only rust binding for all the utility functions so far, I'd keep it that way. They behave closer to expectations, and produce readable errors.

**Comment by noahmayr** [comment]
xplr.util.relative would return "../otherdir" if you pass it "~/Desktop/otherdir" while you're in "~/Desktop/somedir".

**Comment by sayanarijit** [comment]
> Maybe also something like xplr.util.shortest_path which will return either a relative path, absolute path or a path relative to home like "~/something" depending on which is the shortest option. This would be useful for displaying paths while using as few characters as possible (maybe interesting for the selection panel as well, long absolute paths tend to get cut off).

Good idea. But need to find a better name. Maybe something like `compressed_path`.

> Also since I haven't said it anywhere yet, thank you for creating and maintaining this tool. I've been using it for a few weeks now and started hacking it more extensively in the last couple of days. I'll try to create some plugins from the things I've done after cleaning up the logic a bit.

Thank you... Glad you found it useful. Looking forward to the plugins.

**Comment by noahmayr** [comment]
I actually played around with implementing the relative_path function, but I wasn't able to access the current directory of the app in a the util functions and while trying to make it work I went down a rabbit hole of the various ways of sharing reference access to something in rust (since it always needs the up to date app state basically) and after messing with Mutexes, RwLocks, Arcs and so on I gave up because it felt impossible without massive changes to the current architecture.

There might be a simpler way to do this, but I wasn't able to find it.

**Comment by sayanarijit** [comment]
I'd just read from $PWD. A bit of extra computation will be required, but better than nothing I guess.

Another approach would be to pass the pwd as an argument, this will be more flexible as we can reuse it to generate relative paths to any given path, not just $PWD.

**Comment by noahmayr** [comment]
> I'd just read from $PWD. A bit of extra computation will be required, but better than nothing I guess.

I tried that too, but `$PWD` was always set to the initial working directory. One thing I didn't think about though was to always set that env var when we change the app pwd.

> Another approach would be to pass the pwd as an argument, this will be more flexible as we can reuse it to generate relative paths to any given path, not just $PWD. This this case, we can name it `relative_to(pwd, target)`.

Yeah, I just wanted to have $PWD as a default value because most of the time you would probably want a given path made relative to your current directory. For `compressed_path` we would need this as well, because there passing a second path starts making less sense.

**Comment by sayanarijit** [comment]
> I tried that too, but $PWD was always set to the initial working directory. One thing I didn't think about though was to always set that env var when we change the app pwd.

It already does.

**Comment by sayanarijit** [comment]
> I just wanted to have $PWD as a default value because most of the time you would probably want a given path made relative to your current directory.

If it requires reading $PWD for each invocation, I wouldn't use the default, i.e. I'd make it strictly required to pass pwd explicitly.

**Comment by sayanarijit** [comment]
Another name suggestion for `compressed_path`: path_shorthand.

**Comment by noahmayr** [comment]
> If it requires reading $PWD for each invocation, I wouldn't use the default, i.e. I'd make it strictly required to pass pwd explicitly. Even for compressed_path.

Hmm, the problem there is that not all lua functions have access to the current app context and wouldn't be able to get the pwd. (I tried running `os.getenv('PWD')` as well on the lua side, it always returns the dir xplr was started from).

For example a column renderer couldn't render symlinks with relative path to the current dir, without first trying to determine it's current working directory based on the absolute path of the node it's rendering.

What is your concern with reading $PWD in case no base path has been passed? Is it a very time/resource intensive operation? And would computing and passing it in lua really be any better?

**Comment by sayanarijit** [comment]
> Hmm, the problem there is that not all lua functions have access to the current app context and wouldn't be able to get the pwd. (I tried running os.getenv('PWD') as well on the lua side, it always returns the dir xplr was started from).

Weird... Will check.

> What is your concern with reading $PWD in case no base path has been passed? Is it a very time/resource intensive operation? And would computing and passing it in lua really be any better?

It will be used to render the UI, which is the primary concern. I assume it'll be faster to pass it than querying env, but yes, I can be wrong.

**Comment by noahmayr** [comment]
> Hmm right... Lua env doesn't get updated on directory change. Although, pwd should be available as context everywhere, unless you're calling the function during load time, in which case os.getenv should work fine.

Currently the column renderer only gets the resolvednode, not the app context

**Comment by noahmayr** [comment]
> Hmm right... Lua env doesn't get updated on directory change. Although, pwd should be available as context everywhere, unless you're calling the function during load time, in which case os.getenv should work fine.

os.getenv actually gives you the dir xplr is launched from, it would be incorrect when passing a directory as the entry point

**Comment by sayanarijit** [comment]
It's wrong then... Resolved node should be https://xplr.dev/en/column-renderer#canonical

Will check tomorrow.

**Comment by noahmayr** [comment]
Nvm confused the types, I mean the column renderer argument which is also some kind of node with added fields

**Comment by sayanarijit** [comment]
https://xplr.dev/en/column-renderer#parent this should be the pwd equivalent.

**Comment by noahmayr** [comment]
Gave it a try in #568, I decided to make the base directory optional for the path_shorthand one because it can already shorten paths just using your home dir which might be enough for some use cases.

**Comment by sayanarijit** [comment]
I have added more utility functions, for node info, I think keeping it simple and comparing the path with the focus/selected nodes is simple and more intuitive.

For `strip_ansi` I don't see a good usecase and doing it reliably doesn't seem trivial.

Others are pretty much implemented.

**Comment by sayanarijit** [comment]
I'll add xplr.util.node_type to get the style and metadata of a node based on xplr.config.node_types.

**Comment by sayanarijit** [comment]
Here's more improvements: https://github.com/sayanarijit/xplr/pull/582

**Comment by noahmayr** [comment]
I think we can close this then
